// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: account.proto

package account_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccId         int64                  `protobuf:"varint,1,opt,name=Acc_id,json=AccId,proto3" json:"Acc_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	Amt           int64                  `protobuf:"varint,3,opt,name=Amt,proto3" json:"Amt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountRequest) Reset() {
	*x = UpdateAccountRequest{}
	mi := &file_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountRequest) ProtoMessage() {}

func (x *UpdateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateAccountRequest) GetAccId() int64 {
	if x != nil {
		return x.AccId
	}
	return 0
}

func (x *UpdateAccountRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UpdateAccountRequest) GetAmt() int64 {
	if x != nil {
		return x.Amt
	}
	return 0
}

type UpdateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccId         int64                  `protobuf:"varint,1,opt,name=Acc_id,json=AccId,proto3" json:"Acc_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	Amt           int64                  `protobuf:"varint,3,opt,name=Amt,proto3" json:"Amt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountResponse) Reset() {
	*x = UpdateAccountResponse{}
	mi := &file_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountResponse) ProtoMessage() {}

func (x *UpdateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountResponse.ProtoReflect.Descriptor instead.
func (*UpdateAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateAccountResponse) GetAccId() int64 {
	if x != nil {
		return x.AccId
	}
	return 0
}

func (x *UpdateAccountResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UpdateAccountResponse) GetAmt() int64 {
	if x != nil {
		return x.Amt
	}
	return 0
}

type DeleteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccId         int64                  `protobuf:"varint,1,opt,name=Acc_id,json=AccId,proto3" json:"Acc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteAccountRequest) GetAccId() int64 {
	if x != nil {
		return x.AccId
	}
	return 0
}

type DeleteAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountResponse) Reset() {
	*x = DeleteAccountResponse{}
	mi := &file_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountResponse) ProtoMessage() {}

func (x *DeleteAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteAccountResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ReadAllAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllAccountRequest) Reset() {
	*x = ReadAllAccountRequest{}
	mi := &file_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllAccountRequest) ProtoMessage() {}

func (x *ReadAllAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllAccountRequest.ProtoReflect.Descriptor instead.
func (*ReadAllAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{6}
}

type ReadAllAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*ReadAccountResponse `protobuf:"bytes,1,rep,name=Accounts,proto3" json:"Accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllAccountResponse) Reset() {
	*x = ReadAllAccountResponse{}
	mi := &file_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllAccountResponse) ProtoMessage() {}

func (x *ReadAllAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllAccountResponse.ProtoReflect.Descriptor instead.
func (*ReadAllAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{7}
}

func (x *ReadAllAccountResponse) GetAccounts() []*ReadAccountResponse {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type ReadTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransId       int64                  `protobuf:"varint,1,opt,name=Trans_id,json=TransId,proto3" json:"Trans_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTransactionRequest) Reset() {
	*x = ReadTransactionRequest{}
	mi := &file_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTransactionRequest) ProtoMessage() {}

func (x *ReadTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTransactionRequest.ProtoReflect.Descriptor instead.
func (*ReadTransactionRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{8}
}

func (x *ReadTransactionRequest) GetTransId() int64 {
	if x != nil {
		return x.TransId
	}
	return 0
}

type ReadTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int64                  `protobuf:"varint,1,opt,name=From,proto3" json:"From,omitempty"`
	To            int64                  `protobuf:"varint,2,opt,name=To,proto3" json:"To,omitempty"`
	Amt           int64                  `protobuf:"varint,3,opt,name=Amt,proto3" json:"Amt,omitempty"`
	Remark        string                 `protobuf:"bytes,4,opt,name=Remark,proto3" json:"Remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTransactionResponse) Reset() {
	*x = ReadTransactionResponse{}
	mi := &file_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTransactionResponse) ProtoMessage() {}

func (x *ReadTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTransactionResponse.ProtoReflect.Descriptor instead.
func (*ReadTransactionResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{9}
}

func (x *ReadTransactionResponse) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *ReadTransactionResponse) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *ReadTransactionResponse) GetAmt() int64 {
	if x != nil {
		return x.Amt
	}
	return 0
}

func (x *ReadTransactionResponse) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type ReadAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccId         int64                  `protobuf:"varint,1,opt,name=Acc_id,json=AccId,proto3" json:"Acc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAccountRequest) Reset() {
	*x = ReadAccountRequest{}
	mi := &file_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAccountRequest) ProtoMessage() {}

func (x *ReadAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAccountRequest.ProtoReflect.Descriptor instead.
func (*ReadAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{10}
}

func (x *ReadAccountRequest) GetAccId() int64 {
	if x != nil {
		return x.AccId
	}
	return 0
}

type ReadAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccId         int64                  `protobuf:"varint,1,opt,name=Acc_id,json=AccId,proto3" json:"Acc_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	Amt           int64                  `protobuf:"varint,3,opt,name=Amt,proto3" json:"Amt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAccountResponse) Reset() {
	*x = ReadAccountResponse{}
	mi := &file_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAccountResponse) ProtoMessage() {}

func (x *ReadAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAccountResponse.ProtoReflect.Descriptor instead.
func (*ReadAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{11}
}

func (x *ReadAccountResponse) GetAccId() int64 {
	if x != nil {
		return x.AccId
	}
	return 0
}

func (x *ReadAccountResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ReadAccountResponse) GetAmt() int64 {
	if x != nil {
		return x.Amt
	}
	return 0
}

type AccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Amt           int64                  `protobuf:"varint,2,opt,name=Amt,proto3" json:"Amt,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountRequest) Reset() {
	*x = AccountRequest{}
	mi := &file_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRequest) ProtoMessage() {}

func (x *AccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRequest.ProtoReflect.Descriptor instead.
func (*AccountRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{12}
}

func (x *AccountRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AccountRequest) GetAmt() int64 {
	if x != nil {
		return x.Amt
	}
	return 0
}

func (x *AccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccId         int64                  `protobuf:"varint,1,opt,name=Acc_id,json=AccId,proto3" json:"Acc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountResponse) Reset() {
	*x = AccountResponse{}
	mi := &file_account_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountResponse) ProtoMessage() {}

func (x *AccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountResponse.ProtoReflect.Descriptor instead.
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{13}
}

func (x *AccountResponse) GetAccId() int64 {
	if x != nil {
		return x.AccId
	}
	return 0
}

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransId       int64                  `protobuf:"varint,1,opt,name=Trans_id,json=TransId,proto3" json:"Trans_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_account_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{14}
}

func (x *TransactionResponse) GetTransId() int64 {
	if x != nil {
		return x.TransId
	}
	return 0
}

type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int64                  `protobuf:"varint,1,opt,name=From,proto3" json:"From,omitempty"`
	To            int64                  `protobuf:"varint,2,opt,name=To,proto3" json:"To,omitempty"`
	Amt           int64                  `protobuf:"varint,3,opt,name=Amt,proto3" json:"Amt,omitempty"`
	Remark        string                 `protobuf:"bytes,4,opt,name=Remark,proto3" json:"Remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_account_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{15}
}

func (x *TransactionRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *TransactionRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *TransactionRequest) GetAmt() int64 {
	if x != nil {
		return x.Amt
	}
	return 0
}

func (x *TransactionRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

var File_account_proto protoreflect.FileDescriptor

const file_account_proto_rawDesc = "" +
	"\n" +
	"\raccount.proto\x12\raccount_proto\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\bUserName\x18\x01 \x01(\tR\bUserName\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\"7\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05Token\x18\x01 \x01(\tR\x05Token\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\"[\n" +
	"\x14UpdateAccountRequest\x12\x15\n" +
	"\x06Acc_id\x18\x01 \x01(\x03R\x05AccId\x12\x1a\n" +
	"\buserName\x18\x02 \x01(\tR\buserName\x12\x10\n" +
	"\x03Amt\x18\x03 \x01(\x03R\x03Amt\"\\\n" +
	"\x15UpdateAccountResponse\x12\x15\n" +
	"\x06Acc_id\x18\x01 \x01(\x03R\x05AccId\x12\x1a\n" +
	"\buserName\x18\x02 \x01(\tR\buserName\x12\x10\n" +
	"\x03Amt\x18\x03 \x01(\x03R\x03Amt\"-\n" +
	"\x14DeleteAccountRequest\x12\x15\n" +
	"\x06Acc_id\x18\x01 \x01(\x03R\x05AccId\")\n" +
	"\x15DeleteAccountResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\x17\n" +
	"\x15ReadAllAccountRequest\"X\n" +
	"\x16ReadAllAccountResponse\x12>\n" +
	"\bAccounts\x18\x01 \x03(\v2\".account_proto.ReadAccountResponseR\bAccounts\"3\n" +
	"\x16ReadTransactionRequest\x12\x19\n" +
	"\bTrans_id\x18\x01 \x01(\x03R\aTransId\"g\n" +
	"\x17ReadTransactionResponse\x12\x12\n" +
	"\x04From\x18\x01 \x01(\x03R\x04From\x12\x0e\n" +
	"\x02To\x18\x02 \x01(\x03R\x02To\x12\x10\n" +
	"\x03Amt\x18\x03 \x01(\x03R\x03Amt\x12\x16\n" +
	"\x06Remark\x18\x04 \x01(\tR\x06Remark\"+\n" +
	"\x12ReadAccountRequest\x12\x15\n" +
	"\x06Acc_id\x18\x01 \x01(\x03R\x05AccId\"Z\n" +
	"\x13ReadAccountResponse\x12\x15\n" +
	"\x06Acc_id\x18\x01 \x01(\x03R\x05AccId\x12\x1a\n" +
	"\buserName\x18\x02 \x01(\tR\buserName\x12\x10\n" +
	"\x03Amt\x18\x03 \x01(\x03R\x03Amt\"Z\n" +
	"\x0eAccountRequest\x12\x1a\n" +
	"\bUserName\x18\x01 \x01(\tR\bUserName\x12\x10\n" +
	"\x03Amt\x18\x02 \x01(\x03R\x03Amt\x12\x1a\n" +
	"\bPassword\x18\x03 \x01(\tR\bPassword\"(\n" +
	"\x0fAccountResponse\x12\x15\n" +
	"\x06Acc_id\x18\x01 \x01(\x03R\x05AccId\"0\n" +
	"\x13TransactionResponse\x12\x19\n" +
	"\bTrans_id\x18\x01 \x01(\x03R\aTransId\"b\n" +
	"\x12TransactionRequest\x12\x12\n" +
	"\x04From\x18\x01 \x01(\x03R\x04From\x12\x0e\n" +
	"\x02To\x18\x02 \x01(\x03R\x02To\x12\x10\n" +
	"\x03Amt\x18\x03 \x01(\x03R\x03Amt\x12\x16\n" +
	"\x06Remark\x18\x04 \x01(\tR\x06Remark2\xde\x05\n" +
	"\x0eAccountService\x12P\n" +
	"\rCreateAccount\x12\x1d.account_proto.AccountRequest\x1a\x1e.account_proto.AccountResponse\"\x00\x12^\n" +
	"\rGetAllAccount\x12$.account_proto.ReadAllAccountRequest\x1a%.account_proto.ReadAllAccountResponse\"\x00\x12\\\n" +
	"\rDeleteAccount\x12#.account_proto.DeleteAccountRequest\x1a$.account_proto.DeleteAccountResponse\"\x00\x12\\\n" +
	"\rUpdateAccount\x12#.account_proto.UpdateAccountRequest\x1a$.account_proto.UpdateAccountResponse\"\x00\x12V\n" +
	"\vReadAccount\x12!.account_proto.ReadAccountRequest\x1a\".account_proto.ReadAccountResponse\"\x00\x12b\n" +
	"\x0fReadTransaction\x12%.account_proto.ReadTransactionRequest\x1a&.account_proto.ReadTransactionResponse\"\x00\x12\\\n" +
	"\x11CreateTransaction\x12!.account_proto.TransactionRequest\x1a\".account_proto.TransactionResponse\"\x00\x12D\n" +
	"\x05Login\x12\x1b.account_proto.LoginRequest\x1a\x1c.account_proto.LoginResponse\"\x00B\x11Z\x0f./account_protob\x06proto3"

var (
	file_account_proto_rawDescOnce sync.Once
	file_account_proto_rawDescData []byte
)

func file_account_proto_rawDescGZIP() []byte {
	file_account_proto_rawDescOnce.Do(func() {
		file_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)))
	})
	return file_account_proto_rawDescData
}

var file_account_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_account_proto_goTypes = []any{
	(*LoginRequest)(nil),            // 0: account_proto.LoginRequest
	(*LoginResponse)(nil),           // 1: account_proto.LoginResponse
	(*UpdateAccountRequest)(nil),    // 2: account_proto.UpdateAccountRequest
	(*UpdateAccountResponse)(nil),   // 3: account_proto.UpdateAccountResponse
	(*DeleteAccountRequest)(nil),    // 4: account_proto.DeleteAccountRequest
	(*DeleteAccountResponse)(nil),   // 5: account_proto.DeleteAccountResponse
	(*ReadAllAccountRequest)(nil),   // 6: account_proto.ReadAllAccountRequest
	(*ReadAllAccountResponse)(nil),  // 7: account_proto.ReadAllAccountResponse
	(*ReadTransactionRequest)(nil),  // 8: account_proto.ReadTransactionRequest
	(*ReadTransactionResponse)(nil), // 9: account_proto.ReadTransactionResponse
	(*ReadAccountRequest)(nil),      // 10: account_proto.ReadAccountRequest
	(*ReadAccountResponse)(nil),     // 11: account_proto.ReadAccountResponse
	(*AccountRequest)(nil),          // 12: account_proto.AccountRequest
	(*AccountResponse)(nil),         // 13: account_proto.AccountResponse
	(*TransactionResponse)(nil),     // 14: account_proto.TransactionResponse
	(*TransactionRequest)(nil),      // 15: account_proto.TransactionRequest
}
var file_account_proto_depIdxs = []int32{
	11, // 0: account_proto.ReadAllAccountResponse.Accounts:type_name -> account_proto.ReadAccountResponse
	12, // 1: account_proto.AccountService.CreateAccount:input_type -> account_proto.AccountRequest
	6,  // 2: account_proto.AccountService.GetAllAccount:input_type -> account_proto.ReadAllAccountRequest
	4,  // 3: account_proto.AccountService.DeleteAccount:input_type -> account_proto.DeleteAccountRequest
	2,  // 4: account_proto.AccountService.UpdateAccount:input_type -> account_proto.UpdateAccountRequest
	10, // 5: account_proto.AccountService.ReadAccount:input_type -> account_proto.ReadAccountRequest
	8,  // 6: account_proto.AccountService.ReadTransaction:input_type -> account_proto.ReadTransactionRequest
	15, // 7: account_proto.AccountService.CreateTransaction:input_type -> account_proto.TransactionRequest
	0,  // 8: account_proto.AccountService.Login:input_type -> account_proto.LoginRequest
	13, // 9: account_proto.AccountService.CreateAccount:output_type -> account_proto.AccountResponse
	7,  // 10: account_proto.AccountService.GetAllAccount:output_type -> account_proto.ReadAllAccountResponse
	5,  // 11: account_proto.AccountService.DeleteAccount:output_type -> account_proto.DeleteAccountResponse
	3,  // 12: account_proto.AccountService.UpdateAccount:output_type -> account_proto.UpdateAccountResponse
	11, // 13: account_proto.AccountService.ReadAccount:output_type -> account_proto.ReadAccountResponse
	9,  // 14: account_proto.AccountService.ReadTransaction:output_type -> account_proto.ReadTransactionResponse
	14, // 15: account_proto.AccountService.CreateTransaction:output_type -> account_proto.TransactionResponse
	1,  // 16: account_proto.AccountService.Login:output_type -> account_proto.LoginResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_account_proto_init() }
func file_account_proto_init() {
	if File_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_proto_goTypes,
		DependencyIndexes: file_account_proto_depIdxs,
		MessageInfos:      file_account_proto_msgTypes,
	}.Build()
	File_account_proto = out.File
	file_account_proto_goTypes = nil
	file_account_proto_depIdxs = nil
}
