// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: transaction.proto

package transaction_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransId       int64                  `protobuf:"varint,1,opt,name=Trans_id,json=TransId,proto3" json:"Trans_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTransactionRequest) Reset() {
	*x = ReadTransactionRequest{}
	mi := &file_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTransactionRequest) ProtoMessage() {}

func (x *ReadTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTransactionRequest.ProtoReflect.Descriptor instead.
func (*ReadTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *ReadTransactionRequest) GetTransId() int64 {
	if x != nil {
		return x.TransId
	}
	return 0
}

type ReadTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int64                  `protobuf:"varint,1,opt,name=From,proto3" json:"From,omitempty"`
	To            int64                  `protobuf:"varint,2,opt,name=To,proto3" json:"To,omitempty"`
	Amt           int64                  `protobuf:"varint,3,opt,name=Amt,proto3" json:"Amt,omitempty"`
	Remark        string                 `protobuf:"bytes,4,opt,name=Remark,proto3" json:"Remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTransactionResponse) Reset() {
	*x = ReadTransactionResponse{}
	mi := &file_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTransactionResponse) ProtoMessage() {}

func (x *ReadTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTransactionResponse.ProtoReflect.Descriptor instead.
func (*ReadTransactionResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *ReadTransactionResponse) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *ReadTransactionResponse) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *ReadTransactionResponse) GetAmt() int64 {
	if x != nil {
		return x.Amt
	}
	return 0
}

func (x *ReadTransactionResponse) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransId       int64                  `protobuf:"varint,1,opt,name=Trans_id,json=TransId,proto3" json:"Trans_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionResponse) GetTransId() int64 {
	if x != nil {
		return x.TransId
	}
	return 0
}

type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int64                  `protobuf:"varint,1,opt,name=From,proto3" json:"From,omitempty"`
	To            int64                  `protobuf:"varint,2,opt,name=To,proto3" json:"To,omitempty"`
	Amt           int64                  `protobuf:"varint,3,opt,name=Amt,proto3" json:"Amt,omitempty"`
	Remark        string                 `protobuf:"bytes,4,opt,name=Remark,proto3" json:"Remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *TransactionRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *TransactionRequest) GetAmt() int64 {
	if x != nil {
		return x.Amt
	}
	return 0
}

func (x *TransactionRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

var File_transaction_proto protoreflect.FileDescriptor

const file_transaction_proto_rawDesc = "" +
	"\n" +
	"\x11transaction.proto\x12\x11transaction_proto\"3\n" +
	"\x16ReadTransactionRequest\x12\x19\n" +
	"\bTrans_id\x18\x01 \x01(\x03R\aTransId\"g\n" +
	"\x17ReadTransactionResponse\x12\x12\n" +
	"\x04From\x18\x01 \x01(\x03R\x04From\x12\x0e\n" +
	"\x02To\x18\x02 \x01(\x03R\x02To\x12\x10\n" +
	"\x03Amt\x18\x03 \x01(\x03R\x03Amt\x12\x16\n" +
	"\x06Remark\x18\x04 \x01(\tR\x06Remark\"0\n" +
	"\x13TransactionResponse\x12\x19\n" +
	"\bTrans_id\x18\x01 \x01(\x03R\aTransId\"b\n" +
	"\x12TransactionRequest\x12\x12\n" +
	"\x04From\x18\x01 \x01(\x03R\x04From\x12\x0e\n" +
	"\x02To\x18\x02 \x01(\x03R\x02To\x12\x10\n" +
	"\x03Amt\x18\x03 \x01(\x03R\x03Amt\x12\x16\n" +
	"\x06Remark\x18\x04 \x01(\tR\x06Remark2\xe6\x01\n" +
	"\x12TransactionService\x12j\n" +
	"\x0fReadTransaction\x12).transaction_proto.ReadTransactionRequest\x1a*.transaction_proto.ReadTransactionResponse\"\x00\x12d\n" +
	"\x11CreateTransaction\x12%.transaction_proto.TransactionRequest\x1a&.transaction_proto.TransactionResponse\"\x00B%Z#./proto_generated/transaction_protob\x06proto3"

var (
	file_transaction_proto_rawDescOnce sync.Once
	file_transaction_proto_rawDescData []byte
)

func file_transaction_proto_rawDescGZIP() []byte {
	file_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)))
	})
	return file_transaction_proto_rawDescData
}

var file_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_transaction_proto_goTypes = []any{
	(*ReadTransactionRequest)(nil),  // 0: transaction_proto.ReadTransactionRequest
	(*ReadTransactionResponse)(nil), // 1: transaction_proto.ReadTransactionResponse
	(*TransactionResponse)(nil),     // 2: transaction_proto.TransactionResponse
	(*TransactionRequest)(nil),      // 3: transaction_proto.TransactionRequest
}
var file_transaction_proto_depIdxs = []int32{
	0, // 0: transaction_proto.TransactionService.ReadTransaction:input_type -> transaction_proto.ReadTransactionRequest
	3, // 1: transaction_proto.TransactionService.CreateTransaction:input_type -> transaction_proto.TransactionRequest
	1, // 2: transaction_proto.TransactionService.ReadTransaction:output_type -> transaction_proto.ReadTransactionResponse
	2, // 3: transaction_proto.TransactionService.CreateTransaction:output_type -> transaction_proto.TransactionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transaction_proto_init() }
func file_transaction_proto_init() {
	if File_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_proto_depIdxs,
		MessageInfos:      file_transaction_proto_msgTypes,
	}.Build()
	File_transaction_proto = out.File
	file_transaction_proto_goTypes = nil
	file_transaction_proto_depIdxs = nil
}
